version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - misspell
    - noctx
    - prealloc
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/swatto/promtotwilio
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
